[package]
name = "media-types"
version = "0.1.0"
authors = ["Dirkjan Ochtman <dirkjan@ochtman.nl>"]
edition = "2018"

[dependencies]
futures = "0.3.5"
reqwest = "0.10"
scraper = "0.12"
tokio = { version = "0.2.21", features = ["macros"] }
