[package]
name = "media-types"
version = "0.1.0"
authors = ["Dirkjan Ochtman <dirkjan@ochtman.nl>"]
edition = "2018"

[dependencies]
futures = "0.3.5"
reqwest = "0.11"
scraper = "0.13"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
